### ISSUE TITLE
Identify or query geojson layers

### ISSUE THREAD

**Issue by xavirayo** [iag-geo/bootleaf#17]
Is it possible to query or identify geojson layers? or should add them via geoserver?

**Comment by slead** [comment]
You need to have the data in GeoServer or ArcGIS Server in order to run a query, as (to my knowledge) there is no mechanism to run a query against a GeoJSON layer.

However, I think you can set `popup: true` against a GeoJSON layer in order to see a simple popup. Give it a try, and let me know if it doesn't work?

**Comment by xavirayo** [comment]
Ok! thanks again for your answer!

Missatge de Stephen Lead <notifications@github.com> del dia dv., 28 de juny
2019 a les 3:33:

**Comment by xavirayo** [comment]
It worked!
setting popup to true, then you can define alias to your fields within the
GeoJson file the same way you do it when you use the query widget or the
identify button.

Thanks!

Missatge de xavi rayo <xavirayo@gmail.com> del dia dv., 28 de juny 2019 a
les 13:21:

**Comment by slead** [comment]
Glad to hear it!
