### ISSUE TITLE
GeoJSON Layer is Disabled After Zoom

### ISSUE THREAD

**Issue by Michael-Wohlstadter** [iag-geo/bootleaf#38]
First, thank you for your work to update BootLeaf.  I have used Bryan's initial BootLeaf code in the past for a project and I really like the enhancements that you have made to the project.

Second, in the demo, if I have the GeoJSON layers enabled, once I zoom in, they are disabled and the markers are cleared.  Checking the GeoJSON box again does not restore the layer.  My primary use will be to display data stored in GeoJSON so this feature is critical.

Thanks,
Michael

**Comment by slead** [comment]
Hi Michael,

I'm glad you find it useful! 

It looks like there's a bug somewhere in the zoom thresholds code.

If you zoom in to New York, the GeoJSON layers do appear once you're zoomed in closely enough. This is due to the `minZoom: 12` value in the configuration file for these layers. Once you zoom out beyond level 12, the layers switch off again.

The bug is that when the map initially loads, those layers should be off by default. Unfortunately I probably won't have a chance to look into this in the near future. You could try removing the `minZoom` or `maxZoom` value for your GeoJSON layers so they're always visible.

Good luck!

**Comment by Michael-Wohlstadter** [comment]
Thank you for your quick response!

I won't have so many features in the map that it would get cluttered when zoomed out.  So your workaround will work perfectly in my usage.  During the winter (I'm a gardener) I might fork the code and dig in.

Thanks again for your contributions and your response,
Michael

**Comment by slead** [comment]
Fork and dig in - I like it :)
